apiVersion: apps/v1
kind: Deployment
metadata:
  name: matches-deployment
spec:
  selector:
    matchLabels:
      app: matches
  replicas: 1
  template:
    metadata:
      labels:
        app: matches
    spec:
      containers:
        - name: matches
          image: georgeflour/example:matches-image-lab
          ports:
            - containerPort: 80
          
          
          